// Global type declarations for packages without type definitions

// Declare all modules that are missing type definitions
declare module '@ampproject/*' {}
declare module '@babel/*' {}
declare module '@chakra-ui/*' {}
declare module '@emotion/*' {}
declare module '@esbuild/*' {}
declare module '@eslint/*' {}
declare module '@eslint-community/*' {}
declare module '@humanfs/*' {}
declare module '@humanwhocodes/*' {}
declare module '@jridgewell/*' {}
declare module '@nodelib/*' {}
declare module '@popperjs/*' {}
declare module '@remix-run/*' {}
declare module '@rolldown/*' {}
declare module '@rollup/*' {}
declare module '@types/*' {}
declare module '@typescript-eslint/*' {}
declare module '@vitejs/*' {}
declare module '@zag-js/*' {}

// Individual modules
declare module 'argparse' {}
declare module 'asynckit' {}
declare module 'babel-plugin-macros' {}
declare module 'balanced-match' {}
declare module 'brace-expansion' {}
declare module 'braces' {}
declare module 'caniuse-lite' {}
declare module 'color-convert' {}
declare module 'color-name' {}
declare module 'combined-stream' {}
declare module 'concat-map' {}
declare module 'convert-source-map' {}
declare module 'cross-spawn' {}
declare module 'debug' {}
declare module 'deep-is' {}
declare module 'delayed-stream' {}
declare module 'dunder-proto' {}
declare module 'electron-to-chromium' {}
declare module 'error-ex' {}
declare module 'eslint-scope' {}
declare module 'espree' {}
declare module 'esquery' {}
declare module 'esrecurse' {}
declare module 'estraverse' {}
declare module 'esutils' {}
declare module 'fast-levenshtein' {}
declare module 'file-entry-cache' {}
declare module 'fill-range' {}
declare module 'find-root' {}
declare module 'flat-cache' {}
declare module 'flatted' {}
declare module 'form-data' {}
declare module 'function-bind' {}
declare module 'gensync' {}
declare module 'get-intrinsic' {}
declare module 'glob-parent' {}
declare module 'globals' {}
declare module 'has' {}
declare module 'has-flag' {}
declare module 'has-property-descriptors' {}
declare module 'has-proto' {}
declare module 'has-symbols' {}
declare module 'hoist-non-react-statics' {}
declare module 'imurmurhash' {}
declare module 'is-arrayish' {}
declare module 'is-core-module' {}
declare module 'is-extglob' {}
declare module 'is-glob' {}
declare module 'is-number' {}
declare module 'isexe' {}
declare module 'js-tokens' {}
declare module 'js-yaml' {}
declare module 'jsesc' {}
declare module 'json-buffer' {}
declare module 'json-parse-even-better-errors' {}
declare module 'json-schema-traverse' {}
declare module 'json-stable-stringify-without-jsonify' {}
declare module 'levn' {}
declare module 'lodash.merge' {}
declare module 'loose-envify' {}
declare module 'lru-cache' {}
declare module 'math-intrinsics' {}
declare module 'merge2' {}
declare module 'micromatch' {}
declare module 'mime-db' {}
declare module 'mime-types' {}
declare module 'minimatch' {}
declare module 'ms' {}
declare module 'natural-compare' {}
declare module 'node-releases' {}
declare module 'normalize-range' {}
declare module 'object-assign' {}
declare module 'optionator' {}
declare module 'parent-module' {}
declare module 'path-parse' {}
declare module 'picomatch' {}
declare module 'prelude-ls' {}
declare module 'prop-types' {}
declare module 'proxy-from-env' {}
declare module 'punycode' {}
declare module 'react-clientside-effect' {}
declare module 'react-is' {}
declare module 'react-refresh' {}
declare module 'resolve' {}
declare module 'resolve-from' {}
declare module 'run-parallel' {}
declare module 'scheduler' {}
declare module 'semver' {}
declare module 'shebang-command' {}
declare module 'source-map' {}
declare module 'stylis' {}
declare module 'supports-color' {}
declare module 'supports-preserve-symlinks-flag' {}
declare module 'tailwindcss' {}
declare module 'to-regex-range' {}
declare module 'toggle-selection' {}
declare module 'type-check' {}
declare module 'use-sync-external-store' {}
declare module 'which' {}
declare module 'yallist' {}